apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-depl-redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: depl-redis
  minReplicas: 15
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50 # Scale up if CPU of POD up to 50%
