apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depl-nginx
  template:
    metadata:
      labels:
        app: depl-nginx
    spec:
      containers:
        - name: depl-nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
