apiVersion: v1
kind: Service
metadata:
  name: svc-test-node-port
spec:
  selector:
    app: svc-test
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 # 30000 - 32767
